// Johannesburg North Venues Data - 20 Real Venues
const johannesburgVenues = [
    {
        name: "Sandton Convention Centre",
        location: "Sandton",
        capacity: 3000,
        contact_email: "info@sandtonconvention.co.za",
        phone_number: "+27 11 517 0000",
        website: "https://www.sandtonconvention.co.za",
        address: "161 Maude Street, Sandown, Sandton, 2196, Johannesburg",
        latitude: -26.1085,
        longitude: 28.0562,
        main_picture: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800&h=600&fit=crop",
        description: "Premier conference and exhibition center in the heart of Sandton, featuring state-of-the-art facilities and flexible event spaces."
    },
    {
        name: "Montecasino",
        location: "Fourways",
        capacity: 2000,
        contact_email: "events@montecasino.co.za",
        phone_number: "+27 11 510 7000",
        website: "https://www.montecasino.co.za",
        address: "Montecasino Boulevard, Fourways, 2055, Johannesburg",
        latitude: -26.0027,
        longitude: 28.0000,
        main_picture: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop",
        description: "Tuscan-themed entertainment complex with multiple event venues, theaters, and conference facilities."
    },
    {
        name: "The Venue at Melrose Arch",
        location: "Melrose Arch",
        capacity: 800,
        contact_email: "events@melrosearch.co.za",
        phone_number: "+27 11 684 0000",
        website: "https://www.melrosearch.co.za",
        address: "Melrose Arch, Melrose, 2196, Johannesburg",
        latitude: -26.1189,
        longitude: 28.0478,
        main_picture: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&h=600&fit=crop",
        description: "Sophisticated urban venue in the heart of Melrose Arch, perfect for corporate events and social gatherings."
    },
    {
        name: "Hyde Park Corner",
        location: "Hyde Park",
        capacity: 500,
        contact_email: "events@hydeparkcorner.co.za",
        phone_number: "+27 11 325 4340",
        website: "https://www.hydeparkcorner.co.za",
        address: "Jan Smuts Avenue, Hyde Park, 2196, Johannesburg",
        latitude: -26.1333,
        longitude: 28.0333,
        main_picture: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&h=600&fit=crop",
        description: "Elegant shopping and entertainment complex with versatile event spaces and premium amenities."
    },
    {
        name: "Rosebank Mall Events Space",
        location: "Rosebank",
        capacity: 400,
        contact_email: "events@rosebankmall.co.za",
        phone_number: "+27 11 447 5000",
        website: "https://www.rosebankmall.co.za",
        address: "Cradock Avenue, Rosebank, 2196, Johannesburg",
        latitude: -26.1425,
        longitude: 28.0444,
        main_picture: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&h=600&fit=crop",
        description: "Modern mall-based venue with flexible event spaces and excellent accessibility."
    },
    {
        name: "The Forum",
        location: "Bryanston",
        capacity: 1200,
        contact_email: "events@theforum.co.za",
        phone_number: "+27 11 463 5000",
        website: "https://www.theforum.co.za",
        address: "Maude Street, Bryanston, 2191, Johannesburg",
        latitude: -26.1085,
        longitude: 28.0562,
        main_picture: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&h=600&fit=crop",
        description: "Iconic entertainment venue with multiple event spaces, perfect for concerts and large gatherings."
    },
    {
        name: "Emperors Palace",
        location: "Kempton Park",
        capacity: 2500,
        contact_email: "events@emperorspalace.co.za",
        phone_number: "+27 11 928 1000",
        website: "https://www.emperorspalace.co.za",
        address: "64 Jones Road, O.R. Tambo, Kempton Park, 1620",
        latitude: -26.1333,
        longitude: 28.2333,
        main_picture: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop",
        description: "Luxury casino and entertainment complex with world-class event facilities and conference centers."
    },
    {
        name: "The Wanderers Club",
        location: "Illovo",
        capacity: 600,
        contact_email: "events@wanderersclub.co.za",
        phone_number: "+27 11 447 9600",
        website: "https://www.wanderersclub.co.za",
        address: "21 North Street, Illovo, 2196, Johannesburg",
        latitude: -26.1333,
        longitude: 28.0333,
        main_picture: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&h=600&fit=crop",
        description: "Historic sports club with elegant event spaces and beautiful gardens for outdoor events."
    },
    {
        name: "The Radisson Blu Hotel Sandton",
        location: "Sandton",
        capacity: 800,
        contact_email: "events.sandton@radissonblu.com",
        phone_number: "+27 11 245 8000",
        website: "https://www.radissonhotels.com",
        address: "Rivonia Road, Sandton, 2196, Johannesburg",
        latitude: -26.1085,
        longitude: 28.0562,
        main_picture: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop",
        description: "Luxury hotel with sophisticated event spaces and world-class catering services."
    },
    {
        name: "The Michelangelo Hotel",
        location: "Sandton",
        capacity: 600,
        contact_email: "events@michelangelohotel.co.za",
        phone_number: "+27 11 282 7000",
        website: "https://www.michelangelohotel.co.za",
        address: "135 West Street, Sandton, 2196, Johannesburg",
        latitude: -26.1085,
        longitude: 28.0562,
        main_picture: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&h=600&fit=crop",
        description: "Iconic 5-star hotel with elegant ballrooms and premium event facilities."
    },
    {
        name: "The Maslow Hotel",
        location: "Sandton",
        capacity: 400,
        contact_email: "events@themaslow.co.za",
        phone_number: "+27 11 290 5000",
        website: "https://www.themaslow.co.za",
        address: "146 Grayston Drive, Sandton, 2196, Johannesburg",
        latitude: -26.1085,
        longitude: 28.0562,
        main_picture: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&h=600&fit=crop",
        description: "Contemporary business hotel with modern event spaces and excellent conference facilities."
    },
    {
        name: "The Saxon Hotel",
        location: "Sandhurst",
        capacity: 300,
        contact_email: "events@thesaxon.co.za",
        phone_number: "+27 11 292 6000",
        website: "https://www.thesaxon.co.za",
        address: "36 Saxon Road, Sandhurst, 2196, Johannesburg",
        latitude: -26.1333,
        longitude: 28.0333,
        main_picture: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop",
        description: "Exclusive boutique hotel with intimate event spaces and personalized service."
    },
    {
        name: "The Westcliff Hotel",
        location: "Westcliff",
        capacity: 500,
        contact_email: "events@westcliff.co.za",
        phone_number: "+27 11 481 6000",
        website: "https://www.westcliff.co.za",
        address: "67 Jan Smuts Avenue, Westcliff, 2193, Johannesburg",
        latitude: -26.1333,
        longitude: 28.0333,
        main_picture: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&h=600&fit=crop",
        description: "Historic luxury hotel with stunning city views and elegant event venues."
    },
    {
        name: "The Four Seasons Hotel",
        location: "Westcliff",
        capacity: 700,
        contact_email: "events.johannesburg@fourseasons.com",
        phone_number: "+27 11 256 2000",
        website: "https://www.fourseasons.com",
        address: "Westcliff, 2193, Johannesburg",
        latitude: -26.1333,
        longitude: 28.0333,
        main_picture: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&h=600&fit=crop",
        description: "World-renowned luxury hotel with exceptional event spaces and impeccable service."
    },
    {
        name: "The Palazzo Hotel",
        location: "Montecasino",
        capacity: 800,
        contact_email: "events@palazzomontecasino.co.za",
        phone_number: "+27 11 510 7000",
        website: "https://www.palazzomontecasino.co.za",
        address: "Montecasino Boulevard, Fourways, 2055, Johannesburg",
        latitude: -26.0027,
        longitude: 28.0000,
        main_picture: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop",
        description: "Luxury hotel within Montecasino complex with versatile event spaces and entertainment options."
    },
    {
        name: "The Indaba Hotel",
        location: "Fourways",
        capacity: 1000,
        contact_email: "events@indabahotel.co.za",
        phone_number: "+27 11 840 6600",
        website: "https://www.indabahotel.co.za",
        address: "William Nicol Drive, Fourways, 2055, Johannesburg",
        latitude: -26.0027,
        longitude: 28.0000,
        main_picture: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&h=600&fit=crop",
        description: "Family-friendly hotel with extensive conference facilities and outdoor event spaces."
    },
    {
        name: "The Dainfern Golf Estate",
        location: "Dainfern",
        capacity: 400,
        contact_email: "events@dainferngolf.co.za",
        phone_number: "+27 11 465 5600",
        website: "https://www.dainferngolf.co.za",
        address: "Dainfern Valley, 2055, Johannesburg",
        latitude: -26.0027,
        longitude: 28.0000,
        main_picture: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&h=600&fit=crop",
        description: "Exclusive golf estate with elegant clubhouse and beautiful outdoor event venues."
    },
    {
        name: "The Bryanston Country Club",
        location: "Bryanston",
        capacity: 300,
        contact_email: "events@bryanstoncountryclub.co.za",
        phone_number: "+27 11 706 2000",
        website: "https://www.bryanstoncountryclub.co.za",
        address: "Bryanston Drive, Bryanston, 2191, Johannesburg",
        latitude: -26.1085,
        longitude: 28.0562,
        main_picture: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop",
        description: "Prestigious country club with sophisticated event spaces and beautiful gardens."
    },
    {
        name: "The Sandton Sun Hotel",
        location: "Sandton",
        capacity: 600,
        contact_email: "events@sandtonsun.co.za",
        phone_number: "+27 11 780 5000",
        website: "https://www.sandtonsun.co.za",
        address: "Corner of Grayston Drive and Fifth Street, Sandton, 2196, Johannesburg",
        latitude: -26.1085,
        longitude: 28.0562,
        main_picture: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&h=600&fit=crop",
        description: "Iconic Sandton hotel with modern event facilities and excellent business amenities."
    },
    {
        name: "The Rosebank Hotel",
        location: "Rosebank",
        capacity: 400,
        contact_email: "events@rosebankhotel.co.za",
        phone_number: "+27 11 447 2700",
        website: "https://www.rosebankhotel.co.za",
        address: "Cradock Avenue, Rosebank, 2196, Johannesburg",
        latitude: -26.1425,
        longitude: 28.0444,
        main_picture: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&h=600&fit=crop",
        description: "Contemporary hotel in the heart of Rosebank with versatile event spaces and modern amenities."
    }
];

module.exports = { johannesburgVenues };
